issue-648: upgrade to rubocop v1.23.0: migrated .rubocop_todo.yml to be compatible with rubocop v1.23.0.
Fixes:

Running rubocop with Ruby version ruby-2.7.3...
.rubocop_todo.yml: Metrics/LineLength has the wrong namespace - should be Layout
Error: The `Lint/HandleExceptions` cop has been renamed to `Lint/SuppressedException`.
(obsolete configuration found in .rubocop_todo.yml, please update it)
The `Naming/UncommunicativeMethodParamName` cop has been renamed to `Naming/MethodParameterName`.
(obsolete configuration found in .rubocop_todo.yml, please update it)