Replace outdated `azurerm_storage_account` argument
The azurerm terraform provider v3.10 no longer accepts the
`azurerm_storage_account` resource argument `allow_blob_public_access`,
so we use the replacement `allow_nested_items_to_be_public` instead.

Fixes:
```
Error: Unsupported argument

  on terraform.tf line 76, in resource "azurerm_storage_account" "azure_bosh_sa":
  76:   allow_blob_public_access = true

An argument named "allow_blob_public_access" is not expected here.
```