Raise an error when network interface is misconfigured
If a specified load balancer is misconfigured such that it doesn't have
any backend address pools the CPI raises this cryptic error:

```
  #<NoMethodError: undefined method `[]' for nil:NilClass>
```

This changes `AzureClient#create_network_interface` to validate the
`nic_params` argument when `load_balancer` or `application_gateway` is
used so that a more semantic error message can be raised.