issue-648: upgrade to rubocop v0.71.0.
Note: v0.71.0 appears to be the firsdt version of rubocop that supports TargetRubyVersion==2.7.

See: rubocop commit c06cc51c541c3ac11ab529c909a8a0f90eefa892. Prior to that commit, we got this error:

Error: Unknown Ruby version 2.7 found in `TargetRubyVersion` parameter (in .rubocop.yml).
Supported versions: 2.2, 2.3, 2.4, 2.5, 2.6